### ISSUE TITLE
Reproducing results with pycocoeval

### ISSUE THREAD

**Issue by quangvnai** [Labbeti/aac-metrics#10]
Hi Labbeti,

I am wondering whether this package can yield the scores (Bleu, CIDEr, Meteor, etc) similar to `pycocoeval` package or not?
Many thanks!

**Comment by Labbeti** [comment]
Hi!
aac-metrics produces the exact same results than the [caption-evaluation-tools](https://github.com/audio-captioning/caption-evaluation-tools) package, which is forked from the [coco-caption](https://github.com/tylin/coco-caption) code. [pycocoevalcap](https://github.com/salaniz/pycocoevalcap) is another fork of coco-caption.
The code of the BLEU, CIDEr and METEOR metrics been updated to python 2 to 3, and a part of the code was cleaned, typed and simplified. The behavior should be the same, so I guess the results are equal or very close to pycocoevalcap, but I haven't tested it.
