### ISSUE TITLE
aac-metrics-download seems to be broken

### ISSUE THREAD

**Issue by alifarrokh** [Labbeti/aac-metrics#11]
Hello

The `aac-metrics-download` command fails because it can't download Stanford CoreNLP from the official link. It seems like the link to CoreNLP zip file is no longer valid, and the version used in aac-metrics (3.6.0) is too old to be downloadable through the [official website](https://stanfordnlp.github.io/CoreNLP/history.html).

How can I fix this?

**Comment by Labbeti** [comment]
Hello!
It seems that all CoreNLP zip files cannot be downloaded (even the most recent one). It looks like the entire site holding the archives (https://nlp.stanford.edu) is down, but this may be a temporary problem.

**Comment by Labbeti** [comment]
The site is back online and CoreNLP files can be downloaded.
