### ISSUE TITLE
Java path checks needs correction

### ISSUE THREAD

**Issue by cipriancorneanu** [Labbeti/aac-metrics#2]
Great work!

In aac_metrics/utils/checks.py(48)check_java_path()

output is not correctly retrieved (empty string) which causes the check to fail even if JAVA version is correct. 

Also aac_metrics/utils/checks.py(51)check_java_path() 
"--version" -> "-version" unless an exception will be thrown.

**Comment by Labbeti** [comment]
Hi! Thank you for your feedback.
I cannot reproduce your error, could you specify your exact java version and distribution? (output of java -version or java --version)

**Comment by Labbeti** [comment]
Has been fixed in version 0.4.2.
