### ISSUE TITLE
install_spice.sh missing in the installation 

### ISSUE THREAD

**Issue by cipriancorneanu** [Labbeti/aac-metrics#3]
Great work!

When running aac-metrics-download it does not find install_spice.sh

If properly referenced and with the additional corrections mentioned in  https://github.com/Labbeti/aac-metrics/issues/2 works like a charm. 

Very useful.

**Comment by Labbeti** [comment]
Hi ! Thanks for your feedback again.
It is fixed in the dev branch and will be fixed in the next version (0.4.2).
