### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by heliossun** [Labbeti/aac-metrics#6]
Thank you for your great work.
I found an issue when use the code. My error is "PTB tokenize error: expected 25000 lines in output file but found 25090." There should be 25000 references, I have no idea what this 25090 is. 
What might be the potential problem of this ?

**Comment by Labbeti** [comment]
Hi! Thanks for reporting this! This error can be caused by a special character like newline '\n' in your one of the sentences, but I cannot be sure without the actual data.

**Comment by heliossun** [comment]
Thank you so much? This is a good point, and it solves my problem properly.

> Hi! Thanks for reporting this! This error can be caused by a special character like newline '\n' in your one of the sentences, but I cannot be sure without the actual data.
