### ISSUE TITLE
METEOR: could not convert string to float: '' on the couple: (['many green trees are in two sides of a curved green river.'], [['many green trees are in two sides of a curved green river .'], ...]

### ISSUE THREAD

**Issue by angelonazzaro** [Labbeti/aac-metrics#9]
Hi! 

I am trying to compute the meteor score on Windows 11 but it keeps giving me hard times. As reported in the title of the issue, whenever I try to compute the meteor score I get the following **error** back: `could not convert string to float: '' on the couple: (['many green trees are in two sides of a curved green river.'], [['many green trees are in two sides of a curved green river .'], ...]`. 

Initially, I thought that it had something to do with the way my model generated the captions, maybe inserting a special character somewhere along the string but it is not the case since I tried to run it manually and it still errors out. 

I tried updating to the latest version and the problem is still there. After a while a decided to debug the computation of the score:
```
candidates: ['many green trees are in two sides of a curved green river.']
mult_references: [['many green trees are in two sides of a curved green river .', 'many green trees are in two sides of a curved green river .', 'many green trees are in two sides of a curved green river .', 'many green trees are in two sides of a curved green river .', 'many green trees are in two sides of a curved green river .']] 
language='en'
stat='13.0 13.0 6.0 6.0 7.0 7.0 6.0 6.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 13.0 13.0'
eval_line='EVAL ||| 13.0 13.0 6.0 6.0 7.0 7.0 6.0 6.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 13.0 13.0'
``` 
When the following line of code is reached: ` meteor_scores_i = float(meteor_process.stdout.readline().strip()) ` the exception is raised. `meteor_process.stdout.readline().strip() ` returns the string `b''` so I would **guess** that there is something wrong when writing to the stdout. 

Any ideas on how to solve it?

**Comment by Labbeti** [comment]
Hi!

Windows / MACOS are not officially supported as I have found that metrics that require an external Java program do not work properly on these systems. I have tried a small workflow on Windows 11 with your data (see below), but unfortunately I cannot reproduce the error.
```py
cands = ["many green trees are in two sides of a curved green river."]
mrefs = [
    [
        "many green trees are in two sides of a curved green river .",
        "many green trees are in two sides of a curved green river .",
        "many green trees are in two sides of a curved green river .",
        "many green trees are in two sides of a curved green river .",
        "many green trees are in two sides of a curved green river .",
    ]
]
meteor_outs_corpus, _ = meteor(cands, mrefs)
print(meteor_outs_corpus["meteor"].item())  # prints 1.0
```
But maybe it is related to your shell or your java version?

**Comment by angelonazzaro** [comment]
Hi, thank you for the response. I have java 11 installed which should be the latest version supported by the meteor metric. 

I tried to switch platforms and I moved from Windows 11 to Ubuntu 20.04 and the errors still remains. At this point I don't  know if the issue is related to the metric itself or to the way I generate the captions. 
Either way, I'll keep updates as soon as I understand something.

**Comment by Labbeti** [comment]
Thanks for the follow-up. This error is really weird, did you try to run the java program directly without using aac-metrics?

**Comment by angelonazzaro** [comment]
Hi, sorry for the the long wait for the follow-up but I had some technical issues on the machine I was using so I had to switch machines. I did the testing on a Mac with an M1 Pro and Sonoma 14.1 using jdk11. 

I run the small snippet of code you made in the previous comment and, surprsingly enough, the **same** error raised once again. At this point, I decided to run the meteor jar manually. 
Given the following parameters:  
```python
cands = ["many green trees are in two sides of a curved green river."]
mrefs = [
    [
        "many green trees are in two sides of a curved green river .",
        "many green trees are in two sides of a curved green river .",
        "many green trees are in two sides of a curved green river .",
        "many green trees are in two sides of a curved green river .",
        "many green trees are in two sides of a curved green river .",
    ]
]
```
I gave as the first input the following string, representing the content of the `encoded_cands_and_mrefs` variable: 

```
SCORE ||| many green trees are in two sides of a curved green river . ||| many green trees are in two sides of a curved green river . ||| many green trees are in two sides of a curved green river . ||| many green trees are in two sides of a curved green river . ||| many green trees are in two sides of a curved green river . ||| many green trees are in two sides of a curved green river.\n
```
After that, I got the following scores 
```
15.0 13.0 6.0 6.0 7.0 7.0 6.0 6.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 13.0 13.0
```
At this point I created the `eval_line` as: 
```
EVAL ||| 15.0 13.0 6.0 6.0 7.0 7.0 6.0 6.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 13.0 13.0\n
```
As soon as I pressed Enter, the jar raised the following exception: 
```java
Exception in thread "main" java.util.InputMismatchException
	at java.base/java.util.Scanner.throwFor(Scanner.java:943)
	at java.base/java.util.Scanner.next(Scanner.java:1598)
	at java.base/java.util.Scanner.nextDouble(Scanner.java:2569)
	at edu.cmu.meteor.scorer.MeteorStats.<init>(Unknown Source)
	at Meteor.scoreStdio(Unknown Source)
	at Meteor.main(Unknown Source)
```
I also tried to pass the encoded version of the `eval_string` returned from `"{}\n".format(eval_line).encode()` but I got a message saying: `Error: specify SCORE or EVAL or SING`. 

Any suggestions?

**Comment by Labbeti** [comment]
Hi again!
Seems like a localization issue to me, because floats cannot be read by the java Scanner object. I can reproduce the same java error if I use the options `-Duser.country=IT -Duser.language=it` to the java program.  Maybe you could try to run `java -Duser.country=US -Duser.language=en -Xmx2G -jar meteor-1.5.jar - - -stdio -norm` ?
By the way, do not use the newline character "\n" at the end of the java program inputs, this is only for simulating the "enter" key in python code.

**Comment by angelonazzaro** [comment]
It worked. I also switched the locale settings to see if the python script would work and It did. 

To add more mystery to the issue itself, in a desperate attempt, before reading your post, I run both the jar and the python script on another machine with Ubuntu 22.04 and python 3.9.5 (this one also had the locale set to Italy) and it worked on the first try. 

I am a bit confused by this behaviour tbh.

**Comment by Labbeti** [comment]
Perfect! I will add this locale options in the next version of aac-metrics to avoid these errors.
For this mystery, maybe the localization detection is different on Ubuntu 22.04 with java 11, I do not know. But it should work anyway with the new options.
